version: '3'
services:
  redis: 
    image: redis
    networks:
      - webnet
  db:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: chat_with_me
  web:
    image: chat-with-me-server
    ports:
      - "8080:8080"
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
      SECRET1: "my name is bajonkels and I do what I want"
      SECRET2: "Kafka was a boy in japan who had lost his mother and his sister"
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "index.js"]
networks:
  webnet:
